version: 0.1

env:
  variables:
    API_BASE: $API_BASE 
    ACCESS_KEY: iaKp1NWkDDL3s8dYE1lTiVrCIAUV3+U5l7f9sAwf
    CODEBUILD_REGION: us-east-1
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - printenv > .env
      - $(aws ecr get-login --region $CODEBUILD_REGION --no-include-email)
  build:
    commands:
      - IMAGE_TAG='echo $CODEBUILD_INITIATOR | cut -d '/' -f2'
      - ENV_NAME='echo $IMAGE_TAG | cut -d '-' -f2'
      - docker build -t $REPOSITORY_URI . --build-arg arg=$ENV_NAME
      - docker tag $REPOSITORY_URI $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG
